// Generated by https://quicktype.io

export interface Comment {
  id: number
  user: User
  comment: string
  numberLike: number
  typeComment: string
  dateModified: string
  isLiked: boolean
  subComment: any[]
  loadMoreCmt: boolean
  tag_friends: any[] | null
  parentId: number
}

export interface User {
  id: number
  name: string
  ava: string
}

export interface GetCommentParams {
  id: number
  type: string
  page?: number
  limit?: number
}

export interface CreateCommentParams {
  target_id: number
  target_type: string
  content: string
  tag_friends?: string
}

export interface DeleteCommentParams {
  cmt_id: number
  content?: string
}
