// Generated by https://quicktype.io

export interface Explore {
  content: string;
  createdAt: null;
  customer: Customer;
  id: number;
  image_experience: string;
  isLiked: boolean;
  media: any[];
  role: string;
  shareBy: ShareBy;
  shareType: string;
  sortContent: string;
  tag_friends: null;
  title: string;
  totalComment: number;
  totalCupon: number;
  totalLike: number;
  totalShare: number;
  tour: any[];
  type: null;
}

export interface Customer {
  avatar: string;
  id: number;
  name: string;
}

export interface ShareBy {
  content: string;
  createdAt: string;
  customer: Customer;
  id: number;
  isLiked: boolean;
  role: number;
  shareType: string;
  sortContent: string;
  tag_friends: null;
  title: string;
  totalComment: number;
  totalCupon: number;
  totalLike: number;
  totalShare: number;
  type: number;
}
